server.error.include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
      username: root
      password: root

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG